[General]
loglevel = notify
skip-proxy = 127.0.0.1, 192.168.0.0/16, 193.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10,localhost,*.local,*.apple.com
exclude-simple-hostnames = true
internet-test-url = http://taobao.com/
proxy-test-url = http://www.gstatic.com/generate_204
allow-wifi-access = true
external-controller-access = psw@0.0.0.0:6170
always-real-ip = *.apple.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com,*.msftncsi.com
test-timeout = 5
network-framework = false
force-http-engine-hosts = router.com, www.router.com
wifi-assist = false
ipv6 = true
ipv6-vif = auto
use-local-host-item-for-proxy = true
read-etc-hosts = false
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
all-hybrid = true
allow-hotspot-access = true
encrypted-dns-server = https://223.5.5.5/dns-query,https://1.1.1.1/dns-query
dns-server = 223.5.5.5, 114.114.114.114, system

[Replica]
hide-apple-request = 1
hide-crashlytics-request = true
hide-udp = 0
keyword-filter-type = none
hide-crash-reporter-request = 1
keyword-filter = (null)

[Proxy]
Ad-Pass = direct
Ad-Block = reject
Ad-GIF = reject-tinygif
Proxy01 = https,adc-us.com,443,username = 用户名,password = 密码
Proxy02 = ss, abc-kt.com, 443, encrypt-method = rc4-md5, password = 密码
Proxy03 = socks5, abc-cn.com, 443, username = 用户名, password = 密码
Proxy04 = vmess, abc-cn.com, 443, username = 用户名, tfo=true
Snell = snell, abc-cn.com, 443, psk=密码, obfs=tls, obfs-host=itunes.apple.com, version=4, reuse=true, tfo=true

[Proxy Group]
Proxy = select, Auto, Scene, Speed, Warp+, no-alert=0, hidden=0
Auto = smart, Snell, Proxy01, Proxy02, Proxy03, Proxy04

[Rule]
AND,((PROCESS-NAME,Telegram), (OR,((IP-CIDR,0.0.0.0/8), (IP-CIDR,224.0.0.0/4)))),REJECT

# RULE-SET
RULE-SET,LAN,DIRECT
RULE-SET,SYSTEM,DIRECT
RULE-SET,https://jkoch14.me/surge-list/ai.list,Proxy
RULE-SET,https://jkoch14.me/surge-list/apple.list,DIRECT
RULE-SET,https://jkoch14.me/surge-list/work.list,Proxy
RULE-SET,https://jkoch14.me/surge-list/reject,REJECT
RULE-SET,https://jkoch14.me/surge-list/cn.list,DIRECT
RULE-SET,https://jkoch14.me/surge-list/telegram.list,Proxy
RULE-SET,https://jkoch14.me/surge-list/proxy.list,Proxy
IP-CIDR6,2409::/16,DIRECT,no-resolve
# GeoIP CN
GEOIP,CN,DIRECT
AND,((PROTOCOL,UDP), (DEST-PORT,443)),REJECT-NO-DROP
FINAL,DIRECT

[Host]
router.com = router
*.taobao.com = server:223.5.5.5
*.jd.com = server:223.5.5.5
*.aliyun.com = server:223.5.5.5
owner-api.vn.tesla.services = server:223.5.5.5

[SSID Setting]
"Apple Store" suspend=true

[MITM]
skip-server-cert-verify = true
tcp-connection = true
h2 = true
hostname = *.google.cn, *.google.com