- name: Generate Loon rules
  shell: bash
  run: |
          set -euo pipefail
          mkdir -p loon

          generate_loon() {
            local input="$1"
            local output="$2"
            local policy="$3"

            awk -v p="$policy" '
              NF && $1 !~ /^#/ {
                if ($0 ~ /,(PROXY|DIRECT|REJECT)$/) {
                  print $0
                } else {
                  print $0 "," p
                }
              }
            ' "$input" > "$output"
          }

          generate_loon ruleset/proxy.txt loon/proxy.txt PROXY
          generate_loon ruleset/direct.txt loon/direct.txt DIRECT
          generate_loon ruleset/reject.txt loon/reject.txt REJECT
          generate_loon ruleset/ai.txt loon/ai.txt PROXY
          generate_loon ruleset/dev.txt loon/dev.txt PROXY
          generate_loon ruleset/edu.txt loon/edu.txt DIRECT
          generate_loon ruleset/gfw.txt loon/gfw.txt PROXY
          generate_loon ruleset/greatfire.txt loon/greatfire.txt PROXY
          generate_loon ruleset/tld-not-cn.txt loon/tld-not-cn.txt PROXY
          generate_loon ruleset/private.txt loon/private.txt DIRECT
          generate_loon ruleset/apple.txt loon/apple.txt DIRECT
          generate_loon ruleset/google.txt loon/google.txt PROXY
          generate_loon ruleset/cncidr.txt loon/cncidr.txt DIRECT
          generate_loon ruleset/telegramcidr.txt loon/telegramcidr.txt PROXY

---
